name: Prod Deployment
on:
  push:
    branches: [ master ] 

jobs:
  deployemnet:
        needs: building JAVA APP
      - name: deploy war to tomact
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: siva1024/scp-deployer@v1.0
        with:
          host: ${{ secrets.MY_HOST }}
          username: ${{ secrets.CLOUD_UNAME }}
          key: ${{ secrets.SSH_TOKEN }}
            ### password: ${{ secrets.CLOUD_PASSWD }} 
          source: /home/runner/work/color-lib/color-lib/target/app.war
          target: /home/ubuntu/tomcat9/webapps/harindra.war 
